#**Superstore Profit Analysis**

In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("Superstore.csv", encoding='latin1')

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09/11/2013,12/11/2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09/11/2013,12/11/2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13/06/2013,17/06/2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11/10/2012,18/10/2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11/10/2012,18/10/2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df.shape

(9994, 21)

In [8]:
df.info

<bound method DataFrame.info of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2013-152156  09/11/2013  12/11/2013    Second Class
1          2  CA-2013-152156  09/11/2013  12/11/2013    Second Class
2          3  CA-2013-138688  13/06/2013  17/06/2013    Second Class
3          4  US-2012-108966  11/10/2012  18/10/2012  Standard Class
4          5  US-2012-108966  11/10/2012  18/10/2012  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2011-110422  22/01/2011  24/01/2011    Second Class
9990    9991  CA-2014-121258  27/02/2014  04/03/2014  Standard Class
9991    9992  CA-2014-121258  27/02/2014  04/03/2014  Standard Class
9992    9993  CA-2014-121258  27/02/2014  04/03/2014  Standard Class
9993    9994  CA-2014-119914  05/05/2014  10/05/2014    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage
...   ...         ...     ...              ...              ...          ...
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]>

In [9]:
df.describe

<bound method NDFrame.describe of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2013-152156  09/11/2013  12/11/2013    Second Class
1          2  CA-2013-152156  09/11/2013  12/11/2013    Second Class
2          3  CA-2013-138688  13/06/2013  17/06/2013    Second Class
3          4  US-2012-108966  11/10/2012  18/10/2012  Standard Class
4          5  US-2012-108966  11/10/2012  18/10/2012  Standard Class
...      ...             ...         ...         ...             ...
9989    9990  CA-2011-110422  22/01/2011  24/01/2011    Second Class
9990    9991  CA-2014-121258  27/02/2014  04/03/2014  Standard Class
9991    9992  CA-2014-121258  27/02/2014  04/03/2014  Standard Class
9992    9993  CA-2014-121258  27/02/2014  04/03/2014  Standard Class
9993    9994  CA-2014-119914  05/05/2014  10/05/2014    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage
...   ...         ...     ...              ...              ...          ...
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]>

In [10]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [13]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

#**Profit Analysis**

This section examines the store’s profitability from multiple angles. We begin by calculating the total profit to see the overall earnings, then break it down by product category, region, and sub-category. This helps identify which products and areas contribute most to revenue and provides insights for improving business performance.

In [14]:
total_profit = df['Profit'].sum()
print("Total Profit of the store: $", total_profit)

Total Profit of the store: $ 286397.0217

***Profit by Product Category***

Identify the product categories that generate the highest profit.

In [15]:
# Total profit for each product category
profit_by_category = df.groupby('Category')['Profit'].sum()

print("Profit by Product Category:")
print(profit_by_category)

# the category with the most profit
top_category = profit_by_category.idxmax()
top_profit = profit_by_category.max()

print("\nThe product category that made the most profit is:", top_category)
print("It made a total profit of $", round(top_profit, 2))

Profit by Product Category:
Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

The product category that made the most profit is: Technology
It made a total profit of $ 145454.95

***Profit by Region***

Determine which geographical regions contribute the most to overall profitability.

In [16]:
# Total profit by Region
profit_by_region = df.groupby('Region')['Profit'].sum()

# Print all region profits
print("Profit by Region:")
print(profit_by_region)

#the region with the most profit
top_region = profit_by_region.idxmax()
top_region_profit = profit_by_region.max()

print("\nThe region that made the most profit is:", top_region)
print("It made a total profit of $", round(top_region_profit, 2))

Profit by Region:
Region
Central     39706.3625
East        91522.7800
South       46749.4303
West       108418.4489
Name: Profit, dtype: float64

The region that made the most profit is: West
It made a total profit of $ 108418.45

***Profit by Sub-Category***

Analysing specific product groups to understand which perform best financially.

In [17]:
# Total profit by Sub-Category
profit_by_subcategory = df.groupby('Sub-Category')['Profit'].sum()

# Print all sub-category profits
print("Profit by Sub-Category:")
print(profit_by_subcategory)

# the sub-category with the most profit
top_subcategory = profit_by_subcategory.idxmax()
top_subcategory_profit = profit_by_subcategory.max()

print("\nThe sub-category that made the most profit is:", top_subcategory)
print("It made a total profit of $", round(top_subcategory_profit, 2))

Profit by Sub-Category:
Sub-Category
Accessories    41936.6357
Appliances     18138.0054
Art             6527.7870
Binders        30221.7633
Bookcases      -3472.5560
Chairs         26590.1663
Copiers        55617.8249
Envelopes       6964.1767
Fasteners        949.5182
Furnishings    13059.1436
Labels          5546.2540
Machines        3384.7569
Paper          34053.5693
Phones         44515.7306
Storage        21278.8264
Supplies       -1189.0995
Tables        -17725.4811
Name: Profit, dtype: float64

The sub-category that made the most profit is: Copiers
It made a total profit of $ 55617.82

In [18]:
with pd.ExcelWriter("Superstore_Analysis_Report.xlsx") as writer:
    profit_by_category.to_excel(writer, sheet_name="By Category", index=False)
    profit_by_region.to_excel(writer, sheet_name="By Region", index=False)
    profit_by_subcategory.to_excel(writer, sheet_name="By Sub-Category", index=False)

In [19]:
from google.colab import files

files.download("Superstore_Analysis_Report.xlsx")

In [20]:
profit_by_category

Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

In [21]:
profit_by_category = df.groupby('Category')['Profit'].sum().reset_index()

profit_by_region = df.groupby('Region')['Profit'].sum().reset_index()

profit_by_subcategory = df.groupby('Sub-Category')['Profit'].sum().reset_index()

In [22]:
df['Category'].unique()

array(['Furniture', 'Office Supplies', 'Technology'], dtype=object)

In [23]:
profit_by_category = df.groupby('Category')['Profit'].sum().reset_index()

profit_by_region = df.groupby('Region')['Profit'].sum().reset_index()

profit_by_subcategory = df.groupby('Sub-Category')['Profit'].sum().reset_index()

In [24]:
profit_by_category

          Category       Profit
0        Furniture   18451.2728
1  Office Supplies  122490.8008
2       Technology  145454.9481

In [25]:
with pd.ExcelWriter("Superstore_Analysis_Report.xlsx") as writer:
    profit_by_category.to_excel(writer, sheet_name="By Category", index=False)
    profit_by_region.to_excel(writer, sheet_name="By Region", index=False)
    profit_by_subcategory.to_excel(writer, sheet_name="By Sub-Category", index=False)

In [26]:
from google.colab import files

files.download("Superstore_Analysis_Report.xlsx")